// ─── Mock Data for Wild Immersion Drawings Dashboard ───────────────────────

export const ecosystems = [
  { id: 1, name: "Forêt Européenne",       emoji: "🌿", color: "#10b981" },
  { id: 2, name: "Forêt Asie-Australie",   emoji: "🐨", color: "#a78bfa" },
  { id: 3, name: "Océans du Monde",         emoji: "🌊", color: "#00d4ff" },
  { id: 4, name: "La Jungle Tropicale",     emoji: "🌴", color: "#22c55e" },
  { id: 5, name: "La Savane",               emoji: "🦁", color: "#f59e0b" },
  { id: 6, name: "Alice In Bloomland",      emoji: "🌸", color: "#ec4899" },
  { id: 7, name: "La Jungle Tropicale Biodôme", emoji: "🦜", color: "#84cc16" },
  { id: 8, name: "Récifs Côtiers",          emoji: "🐠", color: "#06b6d4" },
  { id: 9, name: "Corals",                  emoji: "🪸", color: "#f97316" },
];

// user_ecosystem.csv data — maps userId → ecosystemIds[]
const userEcosystems: Record<number, number[]> = {
  1:  [1,2,3,4,5,6,7,8],
  2:  [1,3,4,5,6,8,9],
  3:  [1,2,3,4,5,6,7,8],
  4:  [1,2,3],
  7:  [2],
  8:  [1,2,3,4],
  9:  [1,2,3,4],
  10: [1,2,3,4,5,6,7,8],
  11: [1,2,3,4],
  12: [1,2,3,4],
  13: [1,2,3,4,5,6,7,8],
  14: [1,2,3,4,5,6],
  15: [1,2,3,4],
  17: [1,2,3,4],
  19: [1,2,3],
  20: [1,2,3],
  21: [3],
  23: [1,2,3,4],
  24: [1,2,3,4,5,6,7,8],
  25: [1,3,4,5,6,8],
  26: [3],
  27: [1,2,3,4],
  29: [1,2,3,4,5],
  31: [2,3,4,5],
  33: [2,3,4,5,6],
  37: [2,3,4,5],
  38: [7],
  39: [1,2,3,4,5],
  41: [1,2,3,4,5,6,7,8],
  42: [1,2,3,4,5],
  43: [1,2,3,4,5],
  44: [1,2,3,4,5],
  45: [5,6],
  46: [1],
  47: [3],
  48: [1,2,3,4,5,6],
  49: [1,3],
  51: [8],
  52: [8],
  53: [1,2,3,4,5,6,7,8,9],
  54: [3,8],
  55: [1,2,3,4,5,6],
  56: [1,2,3,4,5,6,7,8],
  57: [1,2,3,4,5,6,7,8],
  58: [1,3,4,5,6,8],
  59: [1,9],
  60: [1,2,3,4,5,6,7,8,9],
  61: [9],
  62: [1,2,3,4,5,6,7,8,9],
  63: [1,2,3,4,5,6,8],
  64: [9],
};

// Real clients from user.csv — enriched with metadata
export type Client = {
  id: number;
  name: string;
  createdAt: string;
  expiresAt: string | null;
  isActive: boolean;
  lastUsedAt: string | null;
  scrollingEnabled: boolean;
  ecosystemIds: number[];
  isBase?: boolean;
};

const RAW_CLIENTS: Client[] = [
  { id:  1, name: "AdminOctarina",              createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[1]  ?? [] },
  { id:  2, name: "UserOctarina",               createdAt: "2026-03-18", expiresAt: "2026-09-30",   isActive: true,  lastUsedAt: "2026-05-15", scrollingEnabled: true,  ecosystemIds: userEcosystems[2]  ?? [] },
  { id:  7, name: "Plantoys",                   createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[7]  ?? [] },
  { id:  9, name: "Rodolphe Boyer",             createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[9]  ?? [] },
  { id: 10, name: "Adrien Crespinée",           createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[10] ?? [] },
  { id: 11, name: "Isabelle",                   createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[11] ?? [] },
  { id: 12, name: "Pascal",                     createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[12] ?? [] },
  { id: 13, name: "Test",                       createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[13] ?? [] },
  { id: 14, name: "UNAM",                       createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[14] ?? [] },
  { id: 15, name: "VVF",                        createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[15] ?? [] },
  { id: 17, name: "UCPA",                       createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[17] ?? [] },
  { id: 19, name: "Maison de la Réserve",       createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[19] ?? [] },
  { id: 20, name: "Harborland",                 createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[20] ?? [] },
  { id: 21, name: "Belmont Village",            createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[21] ?? [] },
  { id: 23, name: "Kai Liang",                  createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[23] ?? [] },
  { id: 25, name: "Zoo de la Barben",           createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[25] ?? [] },
  { id: 26, name: "Aquarium St-Malo",           createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[26] ?? [] },
  { id: 27, name: "Nida",                       createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[27] ?? [] },
  { id: 28, name: "THEMUSEUM",                  createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: [] },
  { id: 29, name: "HDSB",                       createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[29] ?? [] },
  { id: 31, name: "DMLHT",                      createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[31] ?? [] },
  { id: 33, name: "Royal Botanical Gardens",    createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[33] ?? [] },
  { id: 37, name: "DOLOKIDS",                   createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[37] ?? [] },
  { id: 38, name: "Biodôme de Montréal",        createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[38] ?? [] },
  { id: 39, name: "Zoológico de Quito",         createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[39] ?? [] },
  { id: 40, name: "Smart Rabbit CR",            createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: [] },
  { id: 42, name: "Quito Zoo",                  createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[42] ?? [] },
  { id: 43, name: "Parc Animalier d'Auvergne", createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[43] ?? [] },
  { id: 44, name: "Musée de Sherbrooke",        createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[44] ?? [] },
  { id: 45, name: "Science East",               createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[45] ?? [] },
  { id: 46, name: "Les Loups du Gévaudan",      createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[46] ?? [] },
  { id: 47, name: "Bergen Aquarium",            createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[47] ?? [] },
  { id: 48, name: "The Belize Zoo",             createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[48] ?? [] },
  { id: 49, name: "Nicolas",                    createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[49] ?? [] },
  { id: 51, name: "Aéroport Marseille Provence",createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[51] ?? [] },
  { id: 52, name: "Aéroport Marseille 2",       createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[52] ?? [] },
  { id: 54, name: "4myplanet",                  createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[54] ?? [] },
  { id: 55, name: "El Trompo",                  createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[55] ?? [] },
  { id: 56, name: "Akumal",                     createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[56] ?? [] },
  { id: 57, name: "TinyMDM",                    createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[57] ?? [] },
  { id: 58, name: "Parc Aïn Sebâa Casablanca",  createdAt: "2026-03-18", expiresAt: null,           isActive: true,  lastUsedAt: null,         scrollingEnabled: true,  ecosystemIds: userEcosystems[58] ?? [] },
  { id: 59, name: "Demo Octarina",              createdAt: "2026-03-23", expiresAt: null,           isActive: true,  lastUsedAt: "2026-05-15", scrollingEnabled: false, ecosystemIds: userEcosystems[59] ?? [] },
  { id: 60, name: "Maritime Aquarium",          createdAt: "2026-03-23", expiresAt: null,           isActive: true,  lastUsedAt: "2026-05-13", scrollingEnabled: false, ecosystemIds: userEcosystems[60] ?? [] },
  { id: 61, name: "Ripley's Aquarium",          createdAt: "2026-04-01", expiresAt: "2029-05-15",   isActive: true,  lastUsedAt: "2026-05-15", scrollingEnabled: false, ecosystemIds: userEcosystems[61] ?? [] },
  { id: 63, name: "TestCam",                    createdAt: "2026-04-16", expiresAt: null,           isActive: true,  lastUsedAt: "2026-04-23", scrollingEnabled: true,  ecosystemIds: userEcosystems[63] ?? [] },
];

export { RAW_CLIENTS };



export const overviewStats = {
  totalDrawings: 18_742,
  drawingsToday: 347,
  activeUsers: 1_284,
  activeInstallations: 23,
  avgInteractionTime: "4m 32s",
  totalSessions: 94_310,
  drawingsThisWeek: 2_891,
  completionRate: 78.4,
};

export const usageChartData = [
  { date: "May 1", drawings: 180, sessions: 620, interactions: 1420 },
  { date: "May 2", drawings: 210, sessions: 740, interactions: 1680 },
  { date: "May 3", drawings: 195, sessions: 690, interactions: 1540 },
  { date: "May 4", drawings: 260, sessions: 890, interactions: 2100 },
  { date: "May 5", drawings: 310, sessions: 1040, interactions: 2480 },
  { date: "May 6", drawings: 290, sessions: 960, interactions: 2240 },
  { date: "May 7", drawings: 340, sessions: 1120, interactions: 2660 },
  { date: "May 8", drawings: 380, sessions: 1280, interactions: 2980 },
  { date: "May 9", drawings: 420, sessions: 1400, interactions: 3240 },
  { date: "May 10", drawings: 390, sessions: 1300, interactions: 3020 },
  { date: "May 11", drawings: 450, sessions: 1520, interactions: 3540 },
  { date: "May 12", drawings: 480, sessions: 1620, interactions: 3780 },
  { date: "May 13", drawings: 510, sessions: 1720, interactions: 4020 },
  { date: "May 14", drawings: 440, sessions: 1480, interactions: 3420 },
  { date: "May 15", drawings: 520, sessions: 1760, interactions: 4120 },
  { date: "May 16", drawings: 560, sessions: 1880, interactions: 4380 },
  { date: "May 17", drawings: 590, sessions: 1980, interactions: 4620 },
  { date: "May 18", drawings: 540, sessions: 1820, interactions: 4240 },
  { date: "May 19", drawings: 610, sessions: 2060, interactions: 4820 },
  { date: "May 20", drawings: 347, sessions: 1180, interactions: 2740 },
];

export const weeklyDistribution = [
  { day: "Mon", value: 68 },
  { day: "Tue", value: 85 },
  { day: "Wed", value: 74 },
  { day: "Thu", value: 92 },
  { day: "Fri", value: 88 },
  { day: "Sat", value: 54 },
  { day: "Sun", value: 42 },
];

export const experienceDistribution = [
  { name: "Underwater World", value: 32, color: "#00d4ff" },
  { name: "Safari Adventure", value: 24, color: "#00c9a7" },
  { name: "Arctic Expedition", value: 18, color: "#818cf8" },
  { name: "Tropical Forest", value: 14, color: "#10b981" },
  { name: "Deep Ocean", value: 12, color: "#f59e0b" },
];

export const recentActivities = [
  {
    id: "a1",
    type: "drawing_created",
    user: "Emma D.",
    location: "Musée de l'Océan, Paris",
    experience: "Underwater World",
    time: "2 min ago",
    avatar: "ED",
    color: "#00d4ff",
  },
  {
    id: "a2",
    type: "installation_online",
    location: "Aquarium de Lyon",
    device: "Terminal #3",
    time: "8 min ago",
    color: "#10b981",
  },
  {
    id: "a3",
    type: "drawing_created",
    user: "Lucas M.",
    location: "Zoo de Bordeaux",
    experience: "Safari Adventure",
    time: "14 min ago",
    avatar: "LM",
    color: "#00c9a7",
  },
  {
    id: "a4",
    type: "milestone",
    label: "10,000 drawings reached at Musée National",
    time: "1h ago",
    color: "#f59e0b",
  },
  {
    id: "a5",
    type: "drawing_created",
    user: "Sofia L.",
    location: "Natural History Museum, Brussels",
    experience: "Arctic Expedition",
    time: "1h 20min ago",
    avatar: "SL",
    color: "#818cf8",
  },
  {
    id: "a6",
    type: "installation_offline",
    location: "Cité des Sciences, Paris",
    device: "Terminal #1",
    time: "2h ago",
    color: "#ef4444",
  },
  {
    id: "a7",
    type: "drawing_created",
    user: "Noah B.",
    location: "Oceanopolis, Brest",
    experience: "Deep Ocean",
    time: "2h 15min ago",
    avatar: "NB",
    color: "#00d4ff",
  },
  {
    id: "a8",
    type: "drawing_created",
    user: "Camille R.",
    location: "Aquarium de La Rochelle",
    experience: "Underwater World",
    time: "3h ago",
    avatar: "CR",
    color: "#00c9a7",
  },
];

export const installations = [
  {
    id: "i1",
    name: "Musée de l'Océan",
    city: "Paris",
    country: "France",
    status: "online",
    devices: 4,
    devicesOnline: 4,
    drawingsToday: 124,
    totalDrawings: 4_821,
    avgSession: "5m 12s",
    lastSync: "1 min ago",
    coordinates: { lat: 48.8566, lng: 2.3522 },
  },
  {
    id: "i2",
    name: "Aquarium de Lyon",
    city: "Lyon",
    country: "France",
    status: "online",
    devices: 3,
    devicesOnline: 3,
    drawingsToday: 87,
    totalDrawings: 3_240,
    avgSession: "4m 45s",
    lastSync: "3 min ago",
    coordinates: { lat: 45.764, lng: 4.8357 },
  },
  {
    id: "i3",
    name: "Cité des Sciences",
    city: "Paris",
    country: "France",
    status: "warning",
    devices: 5,
    devicesOnline: 4,
    drawingsToday: 65,
    totalDrawings: 5_102,
    avgSession: "4m 18s",
    lastSync: "12 min ago",
    coordinates: { lat: 48.8939, lng: 2.3879 },
  },
  {
    id: "i4",
    name: "Natural History Museum",
    city: "Brussels",
    country: "Belgium",
    status: "online",
    devices: 2,
    devicesOnline: 2,
    drawingsToday: 43,
    totalDrawings: 1_890,
    avgSession: "3m 55s",
    lastSync: "5 min ago",
    coordinates: { lat: 50.8503, lng: 4.3517 },
  },
  {
    id: "i5",
    name: "Oceanopolis",
    city: "Brest",
    country: "France",
    status: "online",
    devices: 6,
    devicesOnline: 6,
    drawingsToday: 156,
    totalDrawings: 6_430,
    avgSession: "5m 40s",
    lastSync: "2 min ago",
    coordinates: { lat: 48.3904, lng: -4.4861 },
  },
  {
    id: "i6",
    name: "Zoo de Bordeaux",
    city: "Bordeaux",
    country: "France",
    status: "online",
    devices: 3,
    devicesOnline: 3,
    drawingsToday: 98,
    totalDrawings: 2_710,
    avgSession: "4m 22s",
    lastSync: "4 min ago",
    coordinates: { lat: 44.8378, lng: -0.5792 },
  },
  {
    id: "i7",
    name: "Aquarium de La Rochelle",
    city: "La Rochelle",
    country: "France",
    status: "offline",
    devices: 2,
    devicesOnline: 0,
    drawingsToday: 0,
    totalDrawings: 1_340,
    avgSession: "—",
    lastSync: "2h ago",
    coordinates: { lat: 46.1591, lng: -1.1527 },
  },
];

export const drawings = [
  {
    id: "d1",
    title: "Blue Whale Journey",
    author: "Emma D.",
    authorAge: 9,
    location: "Musée de l'Océan, Paris",
    experience: "Underwater World",
    createdAt: "2026-05-20T10:24:00",
    duration: "6m 12s",
    status: "published",
    shared: true,
    color: "#00d4ff",
    gradient: "from-cyan-900/60 to-blue-900/60",
    emoji: "🐋",
  },
  {
    id: "d2",
    title: "Lion Pride",
    author: "Lucas M.",
    authorAge: 11,
    location: "Zoo de Bordeaux",
    experience: "Safari Adventure",
    createdAt: "2026-05-20T09:58:00",
    duration: "4m 45s",
    status: "published",
    shared: true,
    color: "#f59e0b",
    gradient: "from-amber-900/60 to-orange-900/60",
    emoji: "🦁",
  },
  {
    id: "d3",
    title: "Arctic Fox",
    author: "Sofia L.",
    authorAge: 8,
    location: "Natural History Museum, Brussels",
    experience: "Arctic Expedition",
    createdAt: "2026-05-20T09:34:00",
    duration: "5m 28s",
    status: "published",
    shared: false,
    color: "#818cf8",
    gradient: "from-indigo-900/60 to-purple-900/60",
    emoji: "🦊",
  },
  {
    id: "d4",
    title: "Dolphin Dance",
    author: "Noah B.",
    authorAge: 7,
    location: "Oceanopolis, Brest",
    experience: "Deep Ocean",
    createdAt: "2026-05-20T09:12:00",
    duration: "3m 55s",
    status: "published",
    shared: true,
    color: "#00c9a7",
    gradient: "from-teal-900/60 to-emerald-900/60",
    emoji: "🐬",
  },
  {
    id: "d5",
    title: "Flamingo Lake",
    author: "Camille R.",
    authorAge: 10,
    location: "Aquarium de La Rochelle",
    experience: "Tropical Forest",
    createdAt: "2026-05-20T08:47:00",
    duration: "4m 18s",
    status: "pending",
    shared: false,
    color: "#ec4899",
    gradient: "from-pink-900/60 to-rose-900/60",
    emoji: "🦩",
  },
  {
    id: "d6",
    title: "Tiger Stripes",
    author: "Adam T.",
    authorAge: 12,
    location: "Cité des Sciences, Paris",
    experience: "Safari Adventure",
    createdAt: "2026-05-20T08:30:00",
    duration: "7m 02s",
    status: "published",
    shared: true,
    color: "#f97316",
    gradient: "from-orange-900/60 to-amber-900/60",
    emoji: "🐯",
  },
  {
    id: "d7",
    title: "Octopus Garden",
    author: "Léa F.",
    authorAge: 9,
    location: "Aquarium de Lyon",
    experience: "Underwater World",
    createdAt: "2026-05-19T16:22:00",
    duration: "5m 50s",
    status: "published",
    shared: true,
    color: "#a855f7",
    gradient: "from-purple-900/60 to-violet-900/60",
    emoji: "🐙",
  },
  {
    id: "d8",
    title: "Polar Bear",
    author: "Jules M.",
    authorAge: 8,
    location: "Natural History Museum, Brussels",
    experience: "Arctic Expedition",
    createdAt: "2026-05-19T15:45:00",
    duration: "4m 35s",
    status: "flagged",
    shared: false,
    color: "#60a5fa",
    gradient: "from-blue-900/60 to-sky-900/60",
    emoji: "🐻‍❄️",
  },
  {
    id: "d9",
    title: "Sea Turtle",
    author: "Inès V.",
    authorAge: 11,
    location: "Oceanopolis, Brest",
    experience: "Deep Ocean",
    createdAt: "2026-05-19T14:58:00",
    duration: "6m 40s",
    status: "published",
    shared: true,
    color: "#10b981",
    gradient: "from-emerald-900/60 to-green-900/60",
    emoji: "🐢",
  },
];

export const experiences = [
  {
    id: "e1",
    name: "Underwater World",
    category: "Ocean",
    totalInteractions: 48_240,
    avgDuration: "5m 12s",
    completionRate: 84,
    rating: 4.9,
    drawingsGenerated: 6_120,
    trend: +12.4,
    color: "#00d4ff",
    emoji: "🌊",
    featured: true,
    monthlyData: [340, 380, 420, 480, 540, 610, 580, 640, 700, 760, 820, 890],
  },
  {
    id: "e2",
    name: "Safari Adventure",
    category: "Wildlife",
    totalInteractions: 36_180,
    avgDuration: "4m 45s",
    completionRate: 79,
    rating: 4.8,
    drawingsGenerated: 4_890,
    trend: +8.7,
    color: "#f59e0b",
    emoji: "🦁",
    featured: true,
    monthlyData: [280, 310, 340, 380, 410, 450, 420, 480, 510, 550, 590, 630],
  },
  {
    id: "e3",
    name: "Arctic Expedition",
    category: "Polar",
    totalInteractions: 27_390,
    avgDuration: "4m 22s",
    completionRate: 72,
    rating: 4.7,
    drawingsGenerated: 3_640,
    trend: +15.2,
    color: "#818cf8",
    emoji: "❄️",
    featured: false,
    monthlyData: [180, 210, 240, 270, 290, 320, 310, 350, 380, 410, 440, 480],
  },
  {
    id: "e4",
    name: "Tropical Forest",
    category: "Jungle",
    totalInteractions: 21_840,
    avgDuration: "3m 58s",
    completionRate: 68,
    rating: 4.6,
    drawingsGenerated: 2_910,
    trend: +5.1,
    color: "#10b981",
    emoji: "🌴",
    featured: false,
    monthlyData: [140, 160, 180, 200, 210, 230, 220, 250, 270, 290, 310, 330],
  },
  {
    id: "e5",
    name: "Deep Ocean",
    category: "Ocean",
    totalInteractions: 18_920,
    avgDuration: "6m 05s",
    completionRate: 91,
    rating: 4.9,
    drawingsGenerated: 2_420,
    trend: +22.8,
    color: "#3b82f6",
    emoji: "🦑",
    featured: true,
    monthlyData: [120, 140, 160, 180, 200, 230, 220, 260, 290, 320, 360, 400],
  },
];

export const userAnalytics = {
  totalUsers: 94_310,
  returningUsers: 28_420,
  newUsersThisMonth: 6_840,
  avgSessionsPerUser: 2.8,
  avgEngagementTime: "4m 32s",
  ageDistribution: [
    { group: "5–7 ans", count: 18_200, pct: 19 },
    { group: "8–10 ans", count: 34_600, pct: 37 },
    { group: "11–13 ans", count: 28_400, pct: 30 },
    { group: "14+ ans", count: 13_110, pct: 14 },
  ],
  sessionsByHour: [
    { hour: "8h", sessions: 120 },
    { hour: "9h", sessions: 340 },
    { hour: "10h", sessions: 680 },
    { hour: "11h", sessions: 920 },
    { hour: "12h", sessions: 560 },
    { hour: "13h", sessions: 480 },
    { hour: "14h", sessions: 840 },
    { hour: "15h", sessions: 1040 },
    { hour: "16h", sessions: 1180 },
    { hour: "17h", sessions: 860 },
    { hour: "18h", sessions: 420 },
    { hour: "19h", sessions: 180 },
  ],
  topLocations: [
    { name: "Oceanopolis, Brest", sessions: 14_200, pct: 100 },
    { name: "Musée de l'Océan, Paris", sessions: 11_840, pct: 83 },
    { name: "Cité des Sciences, Paris", sessions: 10_120, pct: 71 },
    { name: "Aquarium de Lyon", sessions: 8_340, pct: 59 },
    { name: "Zoo de Bordeaux", sessions: 6_980, pct: 49 },
  ],
  retentionData: [
    { week: "W1", rate: 100 },
    { week: "W2", rate: 68 },
    { week: "W3", rate: 52 },
    { week: "W4", rate: 44 },
    { week: "W5", rate: 38 },
    { week: "W6", rate: 34 },
    { week: "W7", rate: 31 },
    { week: "W8", rate: 29 },
  ],
};

export const exportHistory = [
  {
    id: "exp1",
    name: "Drawings Export — May 2026",
    type: "csv",
    size: "2.4 MB",
    rows: 18_742,
    createdAt: "2026-05-20T08:00:00",
    status: "ready",
  },
  {
    id: "exp2",
    name: "User Sessions — Q1 2026",
    type: "csv",
    size: "8.1 MB",
    rows: 47_280,
    createdAt: "2026-04-01T07:30:00",
    status: "ready",
  },
  {
    id: "exp3",
    name: "Installation Report — April 2026",
    type: "pdf",
    size: "1.2 MB",
    rows: 0,
    createdAt: "2026-05-01T09:00:00",
    status: "ready",
  },
  {
    id: "exp4",
    name: "Drawing Images — Oceanopolis",
    type: "zip",
    size: "142 MB",
    rows: 6_430,
    createdAt: "2026-05-18T14:20:00",
    status: "ready",
  },
  {
    id: "exp5",
    name: "Analytics Dashboard — May 2026",
    type: "pdf",
    size: "890 KB",
    rows: 0,
    createdAt: "2026-05-20T09:45:00",
    status: "generating",
  },
];
